name: adaptive_text
description: Package that contains text widgets that can auto size by provided constrains
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
